### ISSUE TITLE
Support for interactive queries by URL

### ISSUE THREAD

**Issue by ahwagner** [genome/docm#4]
Linking in from other resources to DoCM for gene-level information is currently unavailable. It would be nice if I could go to docm.genome.wustl.edu/genes/PTEN and see the webpage rendered like so: 

![docm_pten](https://cloud.githubusercontent.com/assets/811065/8194730/1d166d4e-1443-11e5-9fa2-f0a2817c7fcd.png)

**Comment by malachig** [comment]
Yeah, this seems super useful.  Is this something you want to look at?  Or @bainscou?  Or do we need @acoffman to help us our first?

We can already do this via the API:
http://docm.genome.wustl.edu/api/v1/variants.json?genes=PTEN

But maybe there is a way to have an incoming URL that sets the display filters...

**Comment by ahwagner** [comment]
I don't mind contributing to this project--if @bainscou doesn't want to take a crack at it himself.

**Comment by malachig** [comment]
Either way I bet @acoffman would give us some pointers on where to start...  :)

**Comment by bainscou** [comment]
Guidance from @acoffman would be awesome! This is a great idea! I have wanted for a while to start incorporating some new features in DoCM, but have not found the time as I am struggling to get the paper together.

**Comment by acoffman** [comment]
Sure thing guys! This was a really small and easy feature to add, so I just went ahead and did it. I've broken it down into lots of small commits, and will explain each one here. Hopefully that will be helpful for adding new features like this in the future! 

The first commit is the easiest. In 4ec8c0b17653be18b49be80711a2471c5b5aad53, I simply add a new route to `config/routes.rb` that matches the desired new endpoint. This maps an HTTP `GET` request to the path `/genes/:name` to a method named `variant_index` in the (as of yet non-existent) `GenesController`. The gene name will be parsed out of the URL path and available in the `params` hash as `:name`.

The next commit (22766967c64ee663f649dc236ba80972b298e8a4) is some prep work. There are two helper methods in `VariantsController` that are used to set up the data structures that will populate the filters in the sidebar. Since we'll need to use them in our new `GenesController` as well, I'm pulling them out into an [`ActiveSupport::Concern`](http://api.rubyonrails.org/classes/ActiveSupport/Concern.html) so that I can use it in both places without duplicating the code. Concerns are basically just module mixins with some nice built in properties.  

The next commit (f6653a72e169f8d7cf658c69f00b6c413b101495) is more housekeeping. There is some logic in the `Filter` module that handles parsing various filterable values out of the `params` hash that I want to be able to call externally, so I extract it into its own method.

Next (898e40fe0d48b9c1a2a9458810066caa6b23f65c) is the meat of the new feature. This is the new controller and method that our route (added in 4ec8c0b17653be18b49be80711a2471c5b5aad53) points to. This method pulls the gene name out of the params hash, then checks the database to make sure its a gene name that we actually have. If not, it just renders an `HTTP 404 not found`. If it does find the gene, it munges the params hash a bit so that it looks like the `GeneFilter` expects, calls the helpers we extracted earlier, and then renders the same view that our existing endpoint uses for the main page.

434674814846a02828572057a4b8ac3c78ee3d9c just addresses a small bug introduced by our new controller. Because this view is in the `variants` directory and we are now rendering it from both the `VariantsController` and `GenesController` we can no longer use relative paths for our partials, we need to use absolute paths.

79b99f573dc7aa87394aeef0897c7c1259d6f970 is the final piece of the puzzle, in that it allows the multiselect boxes to be rendered with some elements already selected in the UI. (In this case our gene name). 

Let me know if you guys have any questions or if that was helpful, etc! I can provide additional explanation or clarity on any part of it that was confusing.

**Comment by obigriffith** [comment]
Thanks Adam. And thanks for the awesome documentation!

**Comment by bainscou** [comment]
Yes, thank you Adam. This is great for us that are still learning :)

**Comment by acoffman** [comment]
I've added a small improvement to this feature that I'll document here.

8578406 makes the gene names in the paths case insensitive (ie both `/genes/FLT3` and `/genes/fLt3` will take you to the same thing). This is accomplished by downcasing the parameter and then doing a comparison against the downcased gene names in the database.

This approach requires the database to manually lowercase each gene name for comparison each time (more or less - it does some smart caching) the query is run. Obviously, this is quite inefficient. For a dataset as small as the genes in DoCM (~60), it doesn't really matter, but in the interest of doing it "right" 999c75ee0196604bdf92901c4b6fbe3f8d1e915b adds a Postgres [functional index](http://www.postgresql.org/docs/9.1/static/indexes-expressional.html) on `lower(genes.name)`. This basically means that the value of the function will be calculated whenever a row is inserted or updated, rather than at query time.

**Comment by malachig** [comment]
Wow, just found time to review all this.  Thanks @acoffman this is amazing.  Super useful to get a detailed walk through on these commits.
