### ISSUE TITLE
VCF validity

### ISSUE THREAD

**Issue by mattdmem** [genome/docm#49]
Hello, the vcf download has "/" and " " in the info field and this breaks at least pyvcf, does this fit VCF spec?
Thanks

Matt

**Comment by acoffman** [comment]
Hi @mattdmem, thanks for the report!

Looking at the spec (https://samtools.github.io/hts-specs/VCFv4.2.pdf) for the `INFO` field, it does appear that white space is not allowed:

> String, no white-space, semi-colons, or equals-signs permitted;  commas are permitted only as delimiters for lists of values

However it does not seem to mention `/` one way or the other.

We will certainly remove the whitespace as its out of spec. If the `/` is breaking common tools, we can look into changing it as well. I believe it was initially selected as a delimiter because `/` is meaningful to https://github.com/genome/joinx.

Are you seeing the whitespace in the `DISEASE` portion of the `INFO` field?

Thanks!
Adam

**Comment by mattdmem** [comment]
Yes white spaces were in the disease field.

Comma would be more appropriate for the PMIDs as it is a list of values - that's usually how you would see it done.

**Comment by acoffman** [comment]
Hi @mattdmem 

We've just deployed an update to address the VCF formatting. 

Disease names will now utilize underscores instead of spaces, and we're using comma delimited lists rather than forward slashes. I see in addition to using this VCF, you've also written an API client. Is there something about the static VCF that you are unable to get via the API? Or do you just need both for different purposes?

Thanks for your interest in DoCM!

Adam

**Comment by mattdmem** [comment]
Thanks for fixing this so quickly.

We have something in house that takes a vcf and gives us coverage over those positions. DoCM is great to check the coverage of "important" sites in cancer. I already had the vcf so it was just a quick look, that's when I noticed the vcf problems.

I hope you don't mind the python wrapper. We have code that queries the API to rank mutations and the wrapper just makes it neater. We use several similar APIs so we already have most of the code to handle these kind of services.
________________________________

**Comment by malachig** [comment]
Agreed, thanks @acoffman!  @mattdmem thanks for using DoCM.  Great to see people using the API.  Thats what its there for.  I suspect' @acoffman was just polling for use cases and feedback.  We are always interested to understand how the resource works/doesn't work for members of the community to help us prioritize bug fixes and feature additions.  :)

**Comment by acoffman** [comment]
@malachig @mattdmem Exactly! If there was some aspect of the API that was lacking and it was forcing you to use the static file, I just wanted to make sure we got that taken care of!
